name: Run Test

on: [push, pull_request]

env:
  ADILO_PUBLIC_KEY: ${{ secrets.ADILO_PUBLIC_KEY }}
  ADILO_SECRET_KEY: ${{ secrets.ADILO_SECRET_KEY }}

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests
        run: make test
